export const LOAD_CHARTS = 'LOAD_CHARTS'
export type LOAD_CHARTS = typeof LOAD_CHARTS

export const TOGGLE_SUGGESTION = 'TOGGLE_SUGGESTION'
export type TOGGLE_SUGGESTION = typeof TOGGLE_SUGGESTION

export const UPDATE_SELECTION = 'UPDATE_SELECTION'
export type UPDATE_SELECTION = typeof UPDATE_SELECTION

export const UPDATE_DATA_TABLE = 'UPDATE_DATA_TABLE'
export type UPDATE_DATA_TABLE = typeof UPDATE_DATA_TABLE

export const UPDATE_DATA_SORT = 'UPDATE_DATA_SORT'
export type UPDATE_DATA_SORT = typeof UPDATE_DATA_SORT