export const LOAD_CHARTS = 'LOAD_CHARTS'
export type LOAD_CHARTS = typeof LOAD_CHARTS

export const TOGGLE_SUGGESTION = 'TOGGLE_SUGGESTION'
export type TOGGLE_SUGGESTION = typeof TOGGLE_SUGGESTION

export const UPDATE_SELECTION = 'UPDATE_SELECTION'
export type UPDATE_SELECTION = typeof UPDATE_SELECTION

export const UPDATE_DATA_TABLE = 'UPDATE_DATA_TABLE'
export type UPDATE_DATA_TABLE = typeof UPDATE_DATA_TABLE

export const UPDATE_DATA_SORT = 'UPDATE_DATA_SORT'
export type UPDATE_DATA_SORT = typeof UPDATE_DATA_SORT

export const UPDATE_DATA_ORDER = 'UPDATE_DATA_ORDER'
export type UPDATE_DATA_ORDER = typeof UPDATE_DATA_ORDER

export const UPDATE_LOTTIE = 'UPDATE_LOTTIE'
export type UPDATE_LOTTIE = typeof UPDATE_LOTTIE

// export const UPDATE_HIDDEN_LOTTIE = 'UPDATE_HIDDEN_LOTTIE'
// export type UPDATE_HIDDEN_LOTTIE = typeof UPDATE_HIDDEN_LOTTIE

export const UPDATE_KEYFRAME_TRACKS = 'UPDATE_KEYFRAME_TRACKS'
export type UPDATE_KEYFRAME_TRACKS = typeof UPDATE_KEYFRAME_TRACKS

export const UPDATE_STATIC_KEYFRAME = 'UPDATE_STATIC_KEYFRAME'
export type UPDATE_STATIC_KEYFRAME = typeof UPDATE_STATIC_KEYFRAME

// export const UPDATE_GEOUPING_AND_TIMING = 'UPDATE_GEOUPING_AND_TIMING'
// export type UPDATE_GEOUPING_AND_TIMING = typeof UPDATE_GEOUPING_AND_TIMING

export const UPDATE_KEYFRAME_CONTAINER_SLIDER = 'UPDATE_KEYFRAME_CONTAINER_SLIDER'
export type UPDATE_KEYFRAME_CONTAINER_SLIDER = typeof UPDATE_KEYFRAME_CONTAINER_SLIDER